from .gates import NOT, AND, NAND, OR, NOR, XOR, XNOR
from .multiplexer import mux
from .demultiplexer import demux
from .evalgate import eval_gate
from .consts import (
    NOT_TRUTH_TABLE, AND_TRUTH_TABLE, NAND_TRUTH_TABLE, OR_TRUTH_TABLE, NOR_TRUTH_TABLE,
    XOR_TRUTH_TABLE, XNOR_TRUTH_TABLE,
    NOT_TRUTH_TABLE_DICT, AND_TRUTH_TABLE_DICT, NAND_TRUTH_TABLE_DICT, OR_TRUTH_TABLE_DICT,
    NOR_TRUTH_TABLE_DICT, XOR_TRUTH_TABLE_DICT, XNOR_TRUTH_TABLE_DICT,
    TRUTH_TABLES, TRUTH_TABLES_DICT
)